m

diff --git a/bin/ova2qcow2 b/bin/ova2qcow2
--- a/bin/ova2qcow2
+++ b/bin/ova2qcow2
@@ -1,27 +1,6 @@
 #!/bin/sh -e
-#L:  MIT License
-#L:
-#l:  Copyright (c) 2023 Harkaitz Agirre, harkaitz.aguirre@gmail.com
-#L:
-#L:  Permission is hereby granted, free of charge, to any person obtaining a copy
-#L:  of this software and associated documentation files (the "Software"), to deal
-#L:  in the Software without restriction, including without limitation the rights
-#L:  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-#L:  copies of the Software, and to permit persons to whom the Software is
-#L:  furnished to do so, subject to the following conditions:
-#L:
-#L:  The above copyright notice and this permission notice shall be included in all
-#L:  copies or substantial portions of the Software.
-#L:
-#L:  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-#L:  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-#L:  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-#L:  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-#L:  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-#L:  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-#L:  SOFTWARE.
 ##:
-#h: Usage: $0 OVA QCOW
+#h: Usage: ova2qcow2 OVA QCOW
 #h:
 #h: Convert VirtualBox OVA format to qcow2.
 ##:
@@ -57,20 +36,11 @@ ova2qcow2() {
     printf '%s\n' "${info}" > "${to}.info"
     rm -rf "${tmpdir}"
 }
-ova2qcow2_error() {
-    echo "${SCRNAME}: error: $*" >&2
-    return 1
-}
-ova2qcow2_info() {
-    echo "${SCRNAME}: $*" >&2
-}
-SCRNAME="`basename "$0"`"
-if test @"${SCRNAME}" = @"ova2qcow2";then
-    if test -n "$1";then
-        ova2qcow2 "$@"
-    else
-        sed -n 's/^ *#h: \{0,1\}//p' "$0" | sed "s|\\\$0|`basename $0`|g"
-        echo ""
-        sed -n 's/^ *#l: \{0,2\}//p' "$0"
-    fi
+ova2qcow2_error() { echo "error: $*" >&2; return 1; }
+ova2qcow2_info()  { echo "$*" >&2; }
+if test @"$(basename "$0")" = @"ova2qcow2"; then
+    case "${1}" in
+        ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0" ;;
+        *)            ova2qcow2 "$@"; exit 0;;
+    esac
 fi
